version: '3.9'
services:
  pgdb:
    container_name: postgres_server2
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: serverdb
    ports:
      - "5432:5432"
    networks:
      - net
    volumes:
      - pgdata:/var/lib/postgresql/data1

  api:
    container_name: server_api
    hostname: api
    build: .
    ports:
      - "800:8080"
      - "801:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTPS_PORT=801
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypass123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - .\Server.API\https:/https/ 
    networks:
      - net
    depends_on:
      - pgdb

  telegraf:
    image: telegraf
    volumes:
        - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    command: telegraf --config /etc/telegraf/telegraf.conf
    container_name: telegraf
    networks:
      - net
    depends_on:
      - api

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=G8jyxaKIIzXe8NOTfztKv4spaIuNCzmfEca3JQRek6CpSvDnaT3QCep0UGUjSFj_yF8QpvyZV_Kf2EoTso4b_A==
    networks:
      - net
    volumes:
      - influxdb_data:/var/lib/influxdb2
    depends_on:
      - telegraf

  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    container_name: grafana
    hostname: grafana
    restart: always
    environment:
      TZ: "Europe/Moscow"
    networks:
      - net
    depends_on:
      - influxdb

networks:
  net:
    driver: bridge

volumes:
  pgdata:
  telegraf-config:
  influxdb_data: